from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.app.main import create_app

OUT_DIR = ROOT / "frontend" / "lib" / "api" / "generated"
OPENAPI_OUT = OUT_DIR / "openapi.json"
TYPES_OUT = OUT_DIR / "control-plane.ts"

TS_HEADER = """// Generated by backend/scripts/export_frontend_contracts.py. DO NOT EDIT.

"""


def render_openapi() -> str:
    payload = create_app().openapi()
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


class TypeScriptRenderer:
    def __init__(self, schemas: dict[str, dict[str, Any]]) -> None:
        self.schemas = schemas
        self.name_map = {name: self._sanitize_name(name) for name in schemas}

    def render(self) -> str:
        lines = [TS_HEADER]
        for name in sorted(self.schemas):
            lines.append(f"export type {self.name_map[name]} = {self.render_schema(self.schemas[name])};\n")
        lines.append(self.render_schema_registry())
        return "\n".join(lines).rstrip() + "\n"

    def render_schema_registry(self) -> str:
        lines = ["export interface ControlPlaneSchemaRegistry {"]
        for name in sorted(self.schemas):
            lines.append(f"  {json.dumps(name)}: {self.name_map[name]};")
        lines.append("}")
        return "\n".join(lines)

    def render_schema(self, schema: dict[str, Any], *, level: int = 0) -> str:
        if "$ref" in schema:
            return self.render_ref(schema["$ref"])

        if "enum" in schema:
            return self.render_union(json.dumps(value) for value in schema["enum"])

        if "const" in schema:
            return json.dumps(schema["const"])

        if "anyOf" in schema:
            return self.render_union(self.render_schema(item, level=level) for item in schema["anyOf"])

        if "oneOf" in schema:
            return self.render_union(self.render_schema(item, level=level) for item in schema["oneOf"])

        if "allOf" in schema:
            return " & ".join(self.render_schema(item, level=level) for item in schema["allOf"])

        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            return self.render_union(self.render_primitive(item) for item in schema_type)

        if schema_type == "array":
            item_type = self.render_schema(schema.get("items", {}), level=level)
            return f"Array<{item_type}>"

        if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
            return self.render_object(schema, level=level)

        if schema_type is not None:
            return self.render_primitive(schema_type)

        return "unknown"

    def render_object(self, schema: dict[str, Any], *, level: int = 0) -> str:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        additional_properties = schema.get("additionalProperties", False)
        indent = "  " * level
        inner = "  " * (level + 1)

        lines = ["{"]
        for key in sorted(properties):
            property_key = key if key.isidentifier() else json.dumps(key)
            optional = "" if key in required else "?"
            lines.append(
                f"{inner}{property_key}{optional}: {self.render_schema(properties[key], level=level + 1)};"
            )

        if additional_properties is True:
            lines.append(f"{inner}[key: string]: unknown;")
        elif isinstance(additional_properties, dict):
            value_type = self.render_schema(additional_properties, level=level + 1)
            lines.append(f"{inner}[key: string]: {value_type};")
        elif not properties and additional_properties is False:
            lines.append(f"{inner}[key: string]: never;")

        lines.append(f"{indent}}}")
        return "\n".join(lines)

    def render_ref(self, ref: str) -> str:
        name = ref.rsplit("/", 1)[-1]
        return self.name_map.get(name, self._sanitize_name(name))

    @staticmethod
    def render_primitive(kind: str) -> str:
        primitives = {
            "boolean": "boolean",
            "integer": "number",
            "null": "null",
            "number": "number",
            "string": "string",
        }
        return primitives.get(kind, "unknown")

    @staticmethod
    def render_union(types: Sequence[str] | Any) -> str:
        seen: list[str] = []
        for item in types:
            if item not in seen:
                seen.append(item)
        return " | ".join(seen) if seen else "unknown"

    @staticmethod
    def _sanitize_name(value: str) -> str:
        candidate = re.sub(r"[^0-9A-Za-z_]", "_", value)
        if not re.match(r"^[A-Za-z_]", candidate):
            candidate = f"_{candidate}"
        return candidate


def render_types(openapi_payload: dict[str, Any]) -> str:
    schemas = openapi_payload.get("components", {}).get("schemas", {})
    renderer = TypeScriptRenderer(schemas)
    return renderer.render()


def write_generated_files() -> None:
    openapi_payload = create_app().openapi()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OPENAPI_OUT.write_text(json.dumps(openapi_payload, ensure_ascii=False, indent=2) + "\n")
    TYPES_OUT.write_text(render_types(openapi_payload))
    print(f"wrote {OPENAPI_OUT.relative_to(ROOT)}")
    print(f"wrote {TYPES_OUT.relative_to(ROOT)}")


def check_generated_files() -> list[str]:
    openapi_payload = create_app().openapi()
    failures: list[str] = []

    expected_openapi = json.dumps(openapi_payload, ensure_ascii=False, indent=2) + "\n"
    expected_types = render_types(openapi_payload)

    if not OPENAPI_OUT.exists():
        failures.append(f"missing {OPENAPI_OUT.relative_to(ROOT)}")
    elif OPENAPI_OUT.read_text() != expected_openapi:
        failures.append(f"stale {OPENAPI_OUT.relative_to(ROOT)}")

    if not TYPES_OUT.exists():
        failures.append(f"missing {TYPES_OUT.relative_to(ROOT)}")
    elif TYPES_OUT.read_text() != expected_types:
        failures.append(f"stale {TYPES_OUT.relative_to(ROOT)}")

    return failures


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated frontend contracts are stale")
    args = parser.parse_args(argv)

    if args.check:
        failures = check_generated_files()
        if failures:
            print("Frontend contract drift detected:")
            for failure in failures:
                print(f"- {failure}")
            return 1
        print("Frontend contracts check passed.")
        return 0

    write_generated_files()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
